AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false

inherit_from:
  - conf/rubocop_gem.yml

# Disable because aggregate_failures is configured globally
RSpec/MultipleExpectations:
  Enabled: false

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/rubocop/cop/ezcater/graphql/not_authorized_scalar_field_spec.rb

RSpec/SpecFilePathSuffix:
  Exclude:
    - spec/rubocop/cop/ezcater/graphql/not_authorized_scalar_field_spec.rb

Gemspec/RequiredRubyVersion:
  Enabled: false
