AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false

inherit_from:
  - conf/rubocop_gem.yml

# Disable because aggregate_failures is configured globally
RSpec/MultipleExpectations:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
