version: 2.1

orbs:
  ruby: circleci/ruby@1.0

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    parallelism: 1
    working_directory: ~/ezcater
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout

      # Bundle install dependencies
      - run: gem install bundler --no-document -v 2.3.7
      - run: bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: bundle clean --force

      # Run Rubocop
      - run: bundle exec rubocop

      # Run rspec
      - run:
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress

      # Save test results for timing analysis
      - store_test_results:
          path: test_results

workflows:
  test_all:
    jobs:
      - test:
          matrix:
            parameters:
              # https://github.com/CircleCI-Public/cimg-ruby
              ruby-version: ["2.6", "2.7", "3.0", "3.1"]
